routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Login area
Route::namespace('App\Auth')
    ->group(function () {

    // Authentication Routes
    Route::get('/', 'LoginController@showLoginForm')->name('start');
    Route::get('login', 'LoginController@showLoginForm')->name('login');

    Route::post('login', 'LoginController@login')->name('login.submit');
    Route::post('logout', 'LoginController@logout')->name('logout');

    // Password Reset Routes
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    // Registration Routes
    # Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    # Route::post('register', 'RegisterController@register');

    // Email Verification Routes
    # Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    # Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
    # Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');
});


// User is logged in
Route::middleware('auth')->group(function () {
    Route::patch('/comment/{comment}', 'CommentController@update')->name('comment.update');
    Route::delete('/comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

Route::middleware('auth')->name('ajax.')->group(function () {
    Route::post('/savedFilters/store', '\App\Filters\SavedFilterController@store')->name('savedFilters.store');
    Route::get('/savedFilters/store_success', '\App\Filters\SavedFilterController@store_success')->name('savedFilters.store_success');
    Route::patch('/savedFilters/update/{filter}', '\App\Filters\SavedFilterController@update')->name('savedFilters.update');
    Route::get('/savedFilters/update_success', '\App\Filters\SavedFilterController@update_success')->name('savedFilters.update_success');
    Route::delete('/savedFilters/destroy/{filter}', '\App\Filters\SavedFilterController@destroy')->name('savedFilters.destroy');
});


Route::namespace('App')
    ->middleware('auth')
    ->name('app.')
    ->group(function () {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard')->middleware('auth');

    Route::get('/amazon', 'AmazonController@index')->name('amazon.index');

    Route::get('/users', 'UserController@index')->name('user.index');
    Route::get('/users/request', 'UserController@request')->name('user.request');
    Route::get('/user/password', 'UserController@showPasswortChangeForm')->name('user.showPasswortChangeForm');
    Route::post('/user/{user}/password', 'UserController@storePasswortChange')->name('user.storePasswortChange');

    Route::resources([
            '/seal' => 'SealController',
            '/allergen' => 'AllergenController',
            '/coupons/area/coupon' => 'CouponController',
            '/productgroup' => 'ProductgroupController',
            '/manufacturer' => 'ManufacturerController',
            '/temporder' => 'TempOrderController',
        ]
    );

    Route::get('/temporder/dashboard/search/', 'TempOrderController@dashboardSearch')->name('temporder.dashboardSearch');
    Route::get('/temporder/{temporder}/address/', 'TempOrderController@getOrderAddress')->name('temporder.getOrderAddress');
    Route::post('/temporder/{temporder}/address/', 'TempOrderController@setOrderAddress')->name('temporder.setOrderAddress');
    Route::get('/temporder/{temporder}/warenkorb/', 'TempOrderController@getOrderWarenkorb')->name('temporder.getOrderWarenkorb');
    Route::post('/temporder/{temporder}/warenkorb/', 'TempOrderController@setOrderWarenkorb')->name('temporder.setOrderWarenkorb');
    Route::get('/temporder/{temporder}/retransmit/', 'TempOrderController@orderRetransmit')->name('temporder.orderRetransmit');
    Route::get('/temporder/{temporder}/retransmitNew/', 'TempOrderController@orderRetransmitNew')->name('temporder.orderRetransmitNew');
    Route::get('/temporder/{temporder}/activetoggle/cron/', 'TempOrderController@toggleCron')->name('temporder.toggleCron');

    Route::get('/coupons/area/statistics/', 'CouponStatisticsController@index')->name('coupon.statistics');
    Route::get('/coupons/area/statistics/csv', 'CouponStatisticsController@exportCsv')->name('coupon.exportCsv');

    Route::get('/coupons/area/coupon/activetoggle/{coupon}', 'CouponController@toggleActive')->name('coupon.toggleActive');
    Route::get('/coupons/area/coupon/details/{coupon}', 'CouponController@details')->name('coupon.details');
    Route::get('/coupons/area/coupon/details/{coupon}/csv', 'CouponController@codesCsv')->name('coupon.codesCsv');

    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/show', 'ReviewsController@show')->name('reviews.show');
    Route::delete('/reviews/destroy', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::post('/reviews', 'ReviewsController@store')->name('reviews.store');

    Route::get('/topCategories', 'TopCategoriesController@index')->name('topCategories.index');
    Route::get('/topCategories/show/{topCategorie}', 'TopCategoriesController@show')->name('topCategories.show');
    Route::get('/topCategories/create', 'TopCategoriesController@create')->name('topCategories.create');
    Route::post('/topCategories', 'TopCategoriesController@store')->name('topCategories.store');
    Route::patch('/topCategories/{topCategorie}', 'TopCategoriesController@update')->name('topCategories.update');
    Route::delete('/topCategories/destroy/{topCategorie}', 'TopCategoriesController@destroy')->name('topCategories.destroy');
    Route::get('/topCategories/activetoggle/{topCategorie}', 'TopCategoriesController@toggleActive')->name('topCategories.toggleActive');


    Route::get('/topCategoriesEng', 'TopCategoriesEngController@index')->name('topCategoriesEng.index');
    Route::get('/topCategoriesEng/show/{topCategorie}', 'TopCategoriesEngController@show')->name('topCategoriesEng.show');
    Route::get('/topCategoriesEng/create', 'TopCategoriesEngController@create')->name('topCategoriesEng.create');
    Route::post('/topCategoriesEng', 'TopCategoriesEngController@store')->name('topCategoriesEng.store');
    Route::patch('/topCategoriesEng/{topCategorie}', 'TopCategoriesEngController@update')->name('topCategoriesEng.update');
    Route::delete('/topCategoriesEng/destroy/{topCategorie}', 'TopCategoriesEngController@destroy')->name('topCategoriesEng.destroy');
    Route::get('/topCategoriesEng/activetoggle/{topCategorie}', 'TopCategoriesEngController@toggleActive')->name('topCategoriesEng.toggleActive');

    Route::get('/gurado', 'GuradoController@index')->name('gurado.index');
    Route::get('/gurado/show', 'GuradoController@show')->name('gurado.show');
    Route::post('/gurado', 'GuradoController@store')->name('gurado.store');

    Route::get('/seal/activetoggle/{seal}', 'SealController@toggleActive')->name('seal.toggleActive');
    Route::get('/allergen/activetoggle/{allergen}', 'AllergenController@toggleActive')->name('allergen.toggleActive');
    Route::get('/productgroup/activetoggle/{productgroup}', 'ProductgroupController@toggleActive')->name('productgroup.toggleActive');
    Route::get('/manufacturer/activetoggle/{manufacturer}', 'ManufacturerController@toggleActive')->name('manufacturer.toggleActive');
    Route::post('/manufacturer/updateOrder', 'ManufacturerController@updateOrder')->name('manufacturer.updateOrder');

        // InvoiceRelease
    Route::namespace('InvoiceRelease')
        ->group(function () {

        Route::resource('/invoicerelease/costcenter', 'CostcenterController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/costcenter/activetoggle/{costcenter}', 'CostcenterController@toggleActive')->name('invoicerelease.costcenter.toggleActive');

        Route::resource('/invoicerelease/bills', 'BillController', ['as' => 'invoicerelease']);
        Route::resource('/invoicerelease/biller', 'BillerController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/ajax/', 'BillerController@showAjax')->name('invoicerelease.ajax');
        Route::get('/invoicerelease/ajax/{biller}', 'BillerController@showAjax')->name('invoicerelease.ajax.biller');

        Route::get('/invoicerelease/csv/bills', 'BillController@csv')->name('invoicerelease.bills.csv');
        Route::post('/invoicerelease/biller/csv', 'BillerController@csv')->name('invoicerelease.biller.csv');
        Route::get('/invoicerelease/bills/pdf/{filename}', 'BillItemController@loadFile')->name('invoicerelease.bills.pdf');

        Route::get('/invoicerelease/transactions/calendar', 'TransactionsController@calendar')->name('invoicerelease.transactions.calendar');
        Route::get('/invoicerelease/transactions/approval', 'TransactionsController@approval')->name('invoicerelease.transactions.approval');
        Route::get('/invoicerelease/transactions/unsettled', 'TransactionsController@unsettled')->name('invoicerelease.transactions.unsettled');
        Route::get('/invoicerelease/transactions/due_yesterday', 'TransactionsController@due_yesterday')->name('invoicerelease.transactions.due_yesterday');
        Route::post('/invoicerelease/transactions/status', 'TransactionsController@setStatus')->name('invoicerelease.transactions.status');
        Route::post('/invoicerelease/transactions/bills', 'TransactionsController@getBillsByDate')->name('invoicerelease.transactions.getBillsByDate');

app/Coupon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    protected $guarded=['id'];

    public $presentation_short = 'Gutschein';
    public $presentation_long = 'Gutscheine';


    public function isValid($einloesungen='')
    {

        if(empty($this->active)) return false;

        $date_now = new \DateTime();
        if(!empty($this->date_from)) {
            $date_from = new \DateTime($this->date_from);
            if ($date_now < $date_from) return false;
        }

        if(!empty($this->date_to)) {
            $date_to = new \DateTime($this->date_to);
            if ($date_now > $date_to) return false;
        }

        if(!empty($this->use_max)) {
            // Berechne Einlösungen aus DB, wenn Wert nicht übergeben.
            if($einloesungen==='') {
                $einloesungen = $this->uses();
            }
            if ($einloesungen >= $this->uses_max() ) return false;
        }

        return true;

    }

    public function uses() {
        return array_sum($this->codes()->withCount('orders')->pluck('orders_count')->toArray());
    }

    public function uses_max() {
        return $this->use_max * $this->multi;
    }

    public function codes() {
        return $this->hasMany('App\CouponCode');
    }

    public function unusedCodes() {
        return $this->hasMany('App\CouponCode')
            ->leftJoin('coupon_codes_orders', 'coupon_codes.id', '=', 'coupon_codes_orders.coupon_code_id')
            ->whereNull('coupon_codes_orders.coupon_code_id')
            ->select('coupon_codes.*'); // ensure that you only select columns from coupon_codes
    }

    public function userCreate()
    {
        return $this->belongsTo('App\User', 'created_by')->withDefault([
            'name' => 'Gelöschter Nutzer',
        ]);
    }

    public function userUpdate()
    {
        return $this->belongsTo('App\User', 'updated_by')->withDefault([
            'name' => 'Gelöschter Nutzer',
        ]);
    }


}

app/Http/Controllers/Api/v1/CouponController.php
<?php

namespace App\Http\Controllers\Api\v1;


use App\Coupon;
use App\Http\Controllers\Api\BaseController;

class CouponController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function show($coupon)
    {


    }




}

resources/views/app/coupon/index.blade.php
@extends('app.layouts.app')
@section('content')
    <div class="container">
        <div class="card content-area">
            <div class="card-innr">
                <div class="card-head">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="card-title card-title-lg">{{ $coupon->presentation_long }}</h4>
                        </div>
                        <div class="col-md-6">
                            <a title="{{ $coupon->presentation_short }} neu anlegen" style="float: right;" href="{{ route('app.coupon.create') }}"><i class="far fa-plus-square fa-2x"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">

                    <div class="col-md-12">

                        <?php
                        $urlQuerry='';
                        if(strpos(url()->full(), '?')) {
                            $urlQuerry = substr(url()->full(), strpos(url()->full(), '?')+1);
                        }
                        if($urlQuerry=='' & strpos(url()->previous(), '?')) {
                            $urlQuerry = substr(url()->previous(), strpos(url()->previous(), '?')+1);
                        }
                        ?>

                        @include('app.coupon.subnavi',['urlQuery' => $urlQuerry])

                        <form id="submit-form" method="get" action="{{ route('app.coupon.index') }}">
                            <input id="filter" name="filter" type="hidden" class="form-control" value="1" >
                            @csrf
                            <div class="input-group">
                                <input id="filter_code" name="filter_code" type="text" class="form-control" placeholder="Gutschein Code" value="{{ old('filter_code') ?? $filter_attributes['filter_code'] ?? '' }}">
                                <div class="input-group-btn" >
                                    <div class="input-group-append">
                                        <select name="filter_art" id="filter_art" style="cursor: pointer; color:#495057; border: 1px solid #ced4da; border-radius: 0px; height: 37px !important;">
                                            @foreach (['0' => 'Jede Art', '1' => 'Art Gutschrift', '2' => 'Art Prozent', '3' => 'Art Gratisprodukt', '4' => 'Art Versandkostenfrei'] as $key=>$value)
                                                <option value="{{ $key }}"{{ old('filter_art') == $key || ( isset($filter_attributes['filter_art']) && $filter_attributes['filter_art'] == $key ) ? 'selected="selected"' : '' }} >{{ $value }} </option>
                                            @endforeach
                                        </select>
                                        <select  name="filter_multi" id="filter_multi" style="cursor: pointer; color:#495057; border: 1px solid #ced4da; border-radius: 0px; height: 37px !important;">
                                            @foreach (['0' => 'Mit Multicodes', '1' => 'Nur Multicodes', '2' => 'Ohne Multicodes'] as $key=>$value)
                                                <option value="{{ $key }}"{{ old('filter_multi') == $key || ( isset($filter_attributes['filter_multi']) && $filter_attributes['filter_multi'] == $key ) ? 'selected="selected"' : '' }} >{{ $value }} </option>
                                            @endforeach
                                        </select>
                                        <select  name="filter_cheaper_check" id="filter_cheaper_check" style="cursor: pointer; color:#495057; border: 1px solid #ced4da; border-radius: 0px; height: 37px !important;">
                                            @foreach (['1' => 'Mit Rabatt Check', '0' => 'Ohne Rabatt Check'] as $key=>$value)
                                                <option value="{{ $key }}"{{ old('filter_cheaper_check') == $key || ( isset($filter_attributes['filter_cheaper_check']) && $filter_attributes['filter_cheaper_check'] == $key ) ? 'selected="selected"' : '' }} >{{ $value }} </option>
                                            @endforeach
                                        </select>
                                        <button style="line-height: unset; padding: 0px; border-radius: 0px " type="submit" class="btn btn-secondary btn-search" >Filtern</button>
                                        <a title="Zurücksetzen"  style="line-height: unset; padding: 0px; border-radius: 0px 4px 4px 0px; line-height: 35px; min-width: 45px"  class="btn btn-secondary "  role="button" href="{{ route('app.coupon.index' ) }}"><i class="fas fa-redo"></i></a>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>

                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped mt-2 mb-3">

                                <thead class="thead-dark">
                                <tr>
                                    @headicons('1')
                                    <th>Code</th>
                                    <th>Einlösungen</th>
                                    <th>Art</th>
                                    <th>Wert</th>
                                    <th>Rabatt Check</th>
                                    <th>Erstellt</th>
                                    @headicons('4', 'fa-cogs')
                                </tr>
                                </thead>
                                <tbody>

                                @forelse ( $coupons AS $coupon )
                                    <?php
                                    $einloesungen_ist = $coupon->uses();
                                    $einloesungen = $einloesungen_ist. ' von '.$coupon->uses_max();
                                    if(empty($coupon->use_max)) {
                                        $einloesungen = $einloesungen_ist. ' von <span style="font-weight:lighter; font-size:20px">&infin;</span>';
                                    }
                                    $art = '';
                                    switch($coupon->art) {
                                        case '1' : $art = 'Gutschrift'; break;
                                        case '2' : $art = 'Prozent'; break;
                                        case '3' : $art = 'Gratisprodukt'; break;
                                        case '4' : $art = 'Versandkostenfrei'; break;
                                    }

                                    $row_color = '';
                                    $info_circle_class = 'text-success'; // green
                                    $info_circle_titel  = 'deaktivieren';

                                    if(!$coupon->isValid($einloesungen_ist)) {
                                        $row_color = '#bdbdbd';
                                        $info_circle_class = 'text-warning'; // gelb-orange
                                        $info_circle_titel = 'auf Grund seiner individuellen Konfiguration inaktiv';
                                        if(!$coupon->active) {
                                            $info_circle_class = 'text-secondary'; // red
                                            $info_circle_titel  = 'aktivieren';
                                        }
                                    }
                                    ?>

                                    <tr style="color: {{$row_color}};">
                                        <td>
                                            <a title="{{ $coupon->presentation_short }} {{ $info_circle_titel }}" class="mr-2"  href="{{ route('app.coupon.toggleActive', $coupon->id) }}" role="button"><i class="fa fa-circle {{ $info_circle_class }}"></i></a>
                                        </td>
                                        <td title="{{ $coupon->description_private }}">
                                            @if($coupon->multi!=1)
                                                <i>{{ $coupon->codes->count() }}x Multicodes</i>
                                            @else
                                                {{ $coupon->codes[0]->code }}
                                            @endif
                                        </td>
                                        <td>{!! $einloesungen  !!}</td>
                                        <td>{{ $art }} </td>
                                        <td>{{ $coupon->value }} </td>
                                        <td>{{ $coupon->cheaper_check ? 'JA' : 'Nein' }} </td>
                                        <td title="{{ $coupon->userCreate->fullName() }}">@date($coupon->created_at)</td>
                                        <td>
                                            <a title="{{ $coupon->presentation_short }} details" class="mr-2" href="{{ route('app.coupon.details', ['coupon'=>$coupon->id, $urlQuerry ] ) }}"><i class="far fa-eye"></i></a>
                                            <a title="{{ $coupon->presentation_short }} Statistik" class="mr-2" href="{{ route('app.coupon.statistics', $urlQuerry.'&filter=1&coupon='.$coupon->id ) }}"><i class="far fa-chart-bar"></i></a>
                                            <a title="{{ $coupon->presentation_short }} bearbeiten" class="mr-2" href="{{ route('app.coupon.show', ['coupon'=>$coupon->id, $urlQuerry] ) }}"><i class="far fa-edit"></i></a>
                                            <a title="{{ $coupon->presentation_short }} löschen" class="mr-2 modal-delete"  href="#"
                                               data-form-info="Wollen Sie die {{ $coupon->presentation_short }} '{{ $coupon->name }}' wirklich endgültig löschen?"
                                               data-form-action="{{route('app.coupon.destroy', ['coupon'=>$coupon->id])}}">
                                                <i class="far fa-trash-alt"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr id=""><td colspan="100%">Keine {{ $coupon->presentation_long }} vorhanden</td></tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row justify-content-md-center">
                {{ $coupons->withQueryString()->links() }}
            </div>

        </div>

@endsection

resources/views/app/coupon/subnavi.blade.php
<ul class="nav nav-tabs-line mb-3">
    <li class="nav-item">
        <a class="nav-link @if(strpos(Route::currentRouteName(), 'index')) active @endif"
           href="{{route('app.coupon.index', $urlQuerry) }}">Übersicht</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @if(strpos(Route::currentRouteName(), 'statistics')) active @endif"
           href="{{route('app.coupon.statistics', $urlQuerry) }}">Auswertung</a>
    </li>
</ul>