routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Login area
Route::namespace('App\Auth')
    ->group(function () {

    // Authentication Routes
    Route::get('/', 'LoginController@showLoginForm')->name('start');
    Route::get('login', 'LoginController@showLoginForm')->name('login');

    Route::post('login', 'LoginController@login')->name('login.submit');
    Route::post('logout', 'LoginController@logout')->name('logout');

    // Password Reset Routes
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    // Registration Routes
    # Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    # Route::post('register', 'RegisterController@register');

    // Email Verification Routes
    # Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    # Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
    # Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');
});


// User is logged in
Route::middleware('auth')->group(function () {
    Route::patch('/comment/{comment}', 'CommentController@update')->name('comment.update');
    Route::delete('/comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

Route::middleware('auth')->name('ajax.')->group(function () {
    Route::post('/savedFilters/store', '\App\Filters\SavedFilterController@store')->name('savedFilters.store');
    Route::get('/savedFilters/store_success', '\App\Filters\SavedFilterController@store_success')->name('savedFilters.store_success');
    Route::patch('/savedFilters/update/{filter}', '\App\Filters\SavedFilterController@update')->name('savedFilters.update');
    Route::get('/savedFilters/update_success', '\App\Filters\SavedFilterController@update_success')->name('savedFilters.update_success');
    Route::delete('/savedFilters/destroy/{filter}', '\App\Filters\SavedFilterController@destroy')->name('savedFilters.destroy');
});


Route::namespace('App')
    ->middleware('auth')
    ->name('app.')
    ->group(function () {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard')->middleware('auth');

    Route::get('/amazon', 'AmazonController@index')->name('amazon.index');

    Route::get('/users', 'UserController@index')->name('user.index');
    Route::get('/users/request', 'UserController@request')->name('user.request');
    Route::get('/user/password', 'UserController@showPasswortChangeForm')->name('user.showPasswortChangeForm');
    Route::post('/user/{user}/password', 'UserController@storePasswortChange')->name('user.storePasswortChange');

    Route::resources([
            '/seal' => 'SealController',
            '/allergen' => 'AllergenController',
            '/coupons/area/coupon' => 'CouponController',
            '/productgroup' => 'ProductgroupController',
            '/manufacturer' => 'ManufacturerController',
            '/temporder' => 'TempOrderController',
        ]
    );

    Route::get('/temporder/dashboard/search/', 'TempOrderController@dashboardSearch')->name('temporder.dashboardSearch');
    Route::get('/temporder/{temporder}/address/', 'TempOrderController@getOrderAddress')->name('temporder.getOrderAddress');
    Route::post('/temporder/{temporder}/address/', 'TempOrderController@setOrderAddress')->name('temporder.setOrderAddress');
    Route::get('/temporder/{temporder}/warenkorb/', 'TempOrderController@getOrderWarenkorb')->name('temporder.getOrderWarenkorb');
    Route::post('/temporder/{temporder}/warenkorb/', 'TempOrderController@setOrderWarenkorb')->name('temporder.setOrderWarenkorb');
    Route::get('/temporder/{temporder}/retransmit/', 'TempOrderController@orderRetransmit')->name('temporder.orderRetransmit');
    Route::get('/temporder/{temporder}/retransmitNew/', 'TempOrderController@orderRetransmitNew')->name('temporder.orderRetransmitNew');
    Route::get('/temporder/{temporder}/activetoggle/cron/', 'TempOrderController@toggleCron')->name('temporder.toggleCron');

    Route::get('/coupons/area/statistics/', 'CouponStatisticsController@index')->name('coupon.statistics');
    Route::get('/coupons/area/statistics/csv', 'CouponStatisticsController@exportCsv')->name('coupon.exportCsv');

    Route::get('/coupons/area/coupon/activetoggle/{coupon}', 'CouponController@toggleActive')->name('coupon.toggleActive');
    Route::get('/coupons/area/coupon/details/{coupon}', 'CouponController@details')->name('coupon.details');
    Route::get('/coupons/area/coupon/details/{coupon}/csv', 'CouponController@codesCsv')->name('coupon.codesCsv');

    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/show', 'ReviewsController@show')->name('reviews.show');
    Route::delete('/reviews/destroy', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::post('/reviews', 'ReviewsController@store')->name('reviews.store');

    Route::get('/topCategories', 'TopCategoriesController@index')->name('topCategories.index');
    Route::get('/topCategories/show/{topCategorie}', 'TopCategoriesController@show')->name('topCategories.show');
    Route::get('/topCategories/create', 'TopCategoriesController@create')->name('topCategories.create');
    Route::post('/topCategories', 'TopCategoriesController@store')->name('topCategories.store');
    Route::patch('/topCategories/{topCategorie}', 'TopCategoriesController@update')->name('topCategories.update');
    Route::delete('/topCategories/destroy/{topCategorie}', 'TopCategoriesController@destroy')->name('topCategories.destroy');
    Route::get('/topCategories/activetoggle/{topCategorie}', 'TopCategoriesController@toggleActive')->name('topCategories.toggleActive');


    Route::get('/topCategoriesEng', 'TopCategoriesEngController@index')->name('topCategoriesEng.index');
    Route::get('/topCategoriesEng/show/{topCategorie}', 'TopCategoriesEngController@show')->name('topCategoriesEng.show');
    Route::get('/topCategoriesEng/create', 'TopCategoriesEngController@create')->name('topCategoriesEng.create');
    Route::post('/topCategoriesEng', 'TopCategoriesEngController@store')->name('topCategoriesEng.store');
    Route::patch('/topCategoriesEng/{topCategorie}', 'TopCategoriesEngController@update')->name('topCategoriesEng.update');
    Route::delete('/topCategoriesEng/destroy/{topCategorie}', 'TopCategoriesEngController@destroy')->name('topCategoriesEng.destroy');
    Route::get('/topCategoriesEng/activetoggle/{topCategorie}', 'TopCategoriesEngController@toggleActive')->name('topCategoriesEng.toggleActive');

    Route::get('/gurado', 'GuradoController@index')->name('gurado.index');
    Route::get('/gurado/show', 'GuradoController@show')->name('gurado.show');
    Route::post('/gurado', 'GuradoController@store')->name('gurado.store');

    Route::get('/seal/activetoggle/{seal}', 'SealController@toggleActive')->name('seal.toggleActive');
    Route::get('/allergen/activetoggle/{allergen}', 'AllergenController@toggleActive')->name('allergen.toggleActive');
    Route::get('/productgroup/activetoggle/{productgroup}', 'ProductgroupController@toggleActive')->name('productgroup.toggleActive');
    Route::get('/manufacturer/activetoggle/{manufacturer}', 'ManufacturerController@toggleActive')->name('manufacturer.toggleActive');
    Route::post('/manufacturer/updateOrder', 'ManufacturerController@updateOrder')->name('manufacturer.updateOrder');

        // InvoiceRelease
    Route::namespace('InvoiceRelease')
        ->group(function () {

        Route::resource('/invoicerelease/costcenter', 'CostcenterController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/costcenter/activetoggle/{costcenter}', 'CostcenterController@toggleActive')->name('invoicerelease.costcenter.toggleActive');

        Route::resource('/invoicerelease/bills', 'BillController', ['as' => 'invoicerelease']);
        Route::resource('/invoicerelease/biller', 'BillerController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/ajax/', 'BillerController@showAjax')->name('invoicerelease.ajax');
        Route::get('/invoicerelease/ajax/{biller}', 'BillerController@showAjax')->name('invoicerelease.ajax.biller');

        Route::get('/invoicerelease/csv/bills', 'BillController@csv')->name('invoicerelease.bills.csv');
        Route::post('/invoicerelease/biller/csv', 'BillerController@csv')->name('invoicerelease.biller.csv');
        Route::get('/invoicerelease/bills/pdf/{filename}', 'BillItemController@loadFile')->name('invoicerelease.bills.pdf');

        Route::get('/invoicerelease/transactions/calendar', 'TransactionsController@calendar')->name('invoicerelease.transactions.calendar');
        Route::get('/invoicerelease/transactions/approval', 'TransactionsController@approval')->name('invoicerelease.transactions.approval');
        Route::get('/invoicerelease/transactions/unsettled', 'TransactionsController@unsettled')->name('invoicerelease.transactions.unsettled');
        Route::get('/invoicerelease/transactions/due_yesterday', 'TransactionsController@due_yesterday')->name('invoicerelease.transactions.due_yesterday');
        Route::post('/invoicerelease/transactions/status', 'TransactionsController@setStatus')->name('invoicerelease.transactions.status');
        Route::post('/invoicerelease/transactions/bills', 'TransactionsController@getBillsByDate')->name('invoicerelease.transactions.getBillsByDate');

app/User.php
<?php

namespace App;

use App\Notifications\ResetUserPassword;
use App\Notifications\UserWelcome;
use App\Department;
use App\Http\Controllers\Control\Permissions\HasPermissionsTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HasPermissionsTrait;


    protected $guarded=['id'];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function fullName()
    {
        $name = $this->name;
        if(!empty($this->surname)) $name .= ' '.$this->surname;

        return $name;
    }


    public function level()
    {
        return $this->belongsTo('App\Level');
    }


    public function departments() {
        return $this->belongsToMany(Department::class,'users_departments');
    }

    public function hasDepartment($department) {

        if(is_array($department)) $department = $department[0];
        if(!$department instanceof  Department) {
            $department = Department::where('name', $department)->first();
        }
        return (bool) $this->departments()->where('id', $department->id)->count();
    }



    public function departmentsLeader() {

        // ask only connected departments
        #$array = $this->departments->where('user_id', $this->id)->pluck('slug')->toArray();

        // all departments, even department if not connected to a user
        $array = $this->hasMany('App\Department', 'user_id', 'id')->pluck('slug')->toArray();
        $erg=[];
        foreach ($array AS $value) {
            $erg[$value]=1;
        }
        return $erg;
    }

    public function getDepartmentsBySlug() {
        $array = $this->departments()->pluck('slug')->toArray();
        $erg=[];
        foreach ($array AS $value) {
            $erg[$value]=1;
        }
        return $erg;
    }

    public function auditorForDepartments()
    {
        return $this->belongsToMany('App\Department', 'ir_department_releaseusers', 'user_id', 'department_id');
    }

    public function auditorAndRelatedDepartments()
    {
         return collect([$this->auditorForDepartments, $this->departments])->collapse()->unique('id');
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetUserPassword($token));
    }


    public function sendWelcomeNotification()
    {
        $this->notify(new UserWelcome());
    }


}

app/Http/Controllers/App/UserController.php
<?php

namespace App\Http\Controllers\App;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

use App\User;


class UserController extends Controller
{

  function showPasswortChangeForm() {

      return view('app.user.reset');
  }

  function storePasswortChange(User $user) {

    $attributes = request()->validate([
      'password' => 'required|string|max:32',
    ]);
    if(!empty($attributes['password'])) $user->password = Hash::make($attributes['password']);

    $user->save();

    return redirect(route('app.dashboard'))->withSuccess('Kennwort erfolgreich bearbeitet');

  }


    public function index()
    {
        $users = User::all();
        return view('app.user.index')->with(['users' => $users]);
    }

    public function request()
    {

        return view('app.user.request');
    }


}

resources/views/app/user/index.blade.php
@extends('app.layouts.app')

@section('content')

<div class="container">
    <div class="card content-area">
        <div class="card-innr">
            <div class="card-head">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="card-title card-title-lg">Benutzer Übersicht</h4>
                    </div>
                    <div class="col-md-6">
                        @role('manager')
                        <a title="Neuen Benutzer anfragen" style="float: right;" href="{{ route('app.user.request') }}"><i class="far fa-plus-square fa-2x"></i></a>
                        @endrole
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped mt-2 mb-3">
                            <thead class="thead-dark">
                            <tr>
                                <th>Name</th>
                                <th>E-Mail</th>
                                <th>Telefon</th>
                                <th>Abteilung</th>
                                <th>Letzter login</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ( $users AS $user )
                                <tr id="">
                                    <td>{{ $user->fullname() }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->tel }}</td>
                                    <td>{{ $user->department->name }}</td>
                                    <td>@datetime($user->last_login_at)</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/app/user/request.blade.php
@extends('app.layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                   <p>TODO: Formular mit Benutzer Daten eines neuen Mitarbeites, Auftrag zur Anlage im Backend an die IT.</p>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/user/reset.blade.php
@extends('app.layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Passwort neu vergeben</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('app.user.storePasswortChange', auth()->user()->id) }}">
                        @csrf

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Passwort</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" >

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">Speichern</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection