routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Login area
Route::namespace('App\Auth')
    ->group(function () {

    // Authentication Routes
    Route::get('/', 'LoginController@showLoginForm')->name('start');
    Route::get('login', 'LoginController@showLoginForm')->name('login');

    Route::post('login', 'LoginController@login')->name('login.submit');
    Route::post('logout', 'LoginController@logout')->name('logout');

    // Password Reset Routes
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    // Registration Routes
    # Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    # Route::post('register', 'RegisterController@register');

    // Email Verification Routes
    # Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    # Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
    # Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');
});


// User is logged in
Route::middleware('auth')->group(function () {
    Route::patch('/comment/{comment}', 'CommentController@update')->name('comment.update');
    Route::delete('/comment/{comment}', 'CommentController@destroy')->name('comment.destroy');
});

Route::middleware('auth')->name('ajax.')->group(function () {
    Route::post('/savedFilters/store', '\App\Filters\SavedFilterController@store')->name('savedFilters.store');
    Route::get('/savedFilters/store_success', '\App\Filters\SavedFilterController@store_success')->name('savedFilters.store_success');
    Route::patch('/savedFilters/update/{filter}', '\App\Filters\SavedFilterController@update')->name('savedFilters.update');
    Route::get('/savedFilters/update_success', '\App\Filters\SavedFilterController@update_success')->name('savedFilters.update_success');
    Route::delete('/savedFilters/destroy/{filter}', '\App\Filters\SavedFilterController@destroy')->name('savedFilters.destroy');
});


Route::namespace('App')
    ->middleware('auth')
    ->name('app.')
    ->group(function () {

    Route::get('/dashboard', 'HomeController@index')->name('dashboard')->middleware('auth');

    Route::get('/amazon', 'AmazonController@index')->name('amazon.index');

    Route::get('/users', 'UserController@index')->name('user.index');
    Route::get('/users/request', 'UserController@request')->name('user.request');
    Route::get('/user/password', 'UserController@showPasswortChangeForm')->name('user.showPasswortChangeForm');
    Route::post('/user/{user}/password', 'UserController@storePasswortChange')->name('user.storePasswortChange');

    Route::resources([
            '/seal' => 'SealController',
            '/allergen' => 'AllergenController',
            '/coupons/area/coupon' => 'CouponController',
            '/productgroup' => 'ProductgroupController',
            '/manufacturer' => 'ManufacturerController',
            '/temporder' => 'TempOrderController',
        ]
    );

    Route::get('/temporder/dashboard/search/', 'TempOrderController@dashboardSearch')->name('temporder.dashboardSearch');
    Route::get('/temporder/{temporder}/address/', 'TempOrderController@getOrderAddress')->name('temporder.getOrderAddress');
    Route::post('/temporder/{temporder}/address/', 'TempOrderController@setOrderAddress')->name('temporder.setOrderAddress');
    Route::get('/temporder/{temporder}/warenkorb/', 'TempOrderController@getOrderWarenkorb')->name('temporder.getOrderWarenkorb');
    Route::post('/temporder/{temporder}/warenkorb/', 'TempOrderController@setOrderWarenkorb')->name('temporder.setOrderWarenkorb');
    Route::get('/temporder/{temporder}/retransmit/', 'TempOrderController@orderRetransmit')->name('temporder.orderRetransmit');
    Route::get('/temporder/{temporder}/retransmitNew/', 'TempOrderController@orderRetransmitNew')->name('temporder.orderRetransmitNew');
    Route::get('/temporder/{temporder}/activetoggle/cron/', 'TempOrderController@toggleCron')->name('temporder.toggleCron');

    Route::get('/coupons/area/statistics/', 'CouponStatisticsController@index')->name('coupon.statistics');
    Route::get('/coupons/area/statistics/csv', 'CouponStatisticsController@exportCsv')->name('coupon.exportCsv');

    Route::get('/coupons/area/coupon/activetoggle/{coupon}', 'CouponController@toggleActive')->name('coupon.toggleActive');
    Route::get('/coupons/area/coupon/details/{coupon}', 'CouponController@details')->name('coupon.details');
    Route::get('/coupons/area/coupon/details/{coupon}/csv', 'CouponController@codesCsv')->name('coupon.codesCsv');

    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/show', 'ReviewsController@show')->name('reviews.show');
    Route::delete('/reviews/destroy', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::post('/reviews', 'ReviewsController@store')->name('reviews.store');

    Route::get('/topCategories', 'TopCategoriesController@index')->name('topCategories.index');
    Route::get('/topCategories/show/{topCategorie}', 'TopCategoriesController@show')->name('topCategories.show');
    Route::get('/topCategories/create', 'TopCategoriesController@create')->name('topCategories.create');
    Route::post('/topCategories', 'TopCategoriesController@store')->name('topCategories.store');
    Route::patch('/topCategories/{topCategorie}', 'TopCategoriesController@update')->name('topCategories.update');
    Route::delete('/topCategories/destroy/{topCategorie}', 'TopCategoriesController@destroy')->name('topCategories.destroy');
    Route::get('/topCategories/activetoggle/{topCategorie}', 'TopCategoriesController@toggleActive')->name('topCategories.toggleActive');


    Route::get('/topCategoriesEng', 'TopCategoriesEngController@index')->name('topCategoriesEng.index');
    Route::get('/topCategoriesEng/show/{topCategorie}', 'TopCategoriesEngController@show')->name('topCategoriesEng.show');
    Route::get('/topCategoriesEng/create', 'TopCategoriesEngController@create')->name('topCategoriesEng.create');
    Route::post('/topCategoriesEng', 'TopCategoriesEngController@store')->name('topCategoriesEng.store');
    Route::patch('/topCategoriesEng/{topCategorie}', 'TopCategoriesEngController@update')->name('topCategoriesEng.update');
    Route::delete('/topCategoriesEng/destroy/{topCategorie}', 'TopCategoriesEngController@destroy')->name('topCategoriesEng.destroy');
    Route::get('/topCategoriesEng/activetoggle/{topCategorie}', 'TopCategoriesEngController@toggleActive')->name('topCategoriesEng.toggleActive');

    Route::get('/gurado', 'GuradoController@index')->name('gurado.index');
    Route::get('/gurado/show', 'GuradoController@show')->name('gurado.show');
    Route::post('/gurado', 'GuradoController@store')->name('gurado.store');

    Route::get('/seal/activetoggle/{seal}', 'SealController@toggleActive')->name('seal.toggleActive');
    Route::get('/allergen/activetoggle/{allergen}', 'AllergenController@toggleActive')->name('allergen.toggleActive');
    Route::get('/productgroup/activetoggle/{productgroup}', 'ProductgroupController@toggleActive')->name('productgroup.toggleActive');
    Route::get('/manufacturer/activetoggle/{manufacturer}', 'ManufacturerController@toggleActive')->name('manufacturer.toggleActive');
    Route::post('/manufacturer/updateOrder', 'ManufacturerController@updateOrder')->name('manufacturer.updateOrder');

        // InvoiceRelease
    Route::namespace('InvoiceRelease')
        ->group(function () {

        Route::resource('/invoicerelease/costcenter', 'CostcenterController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/costcenter/activetoggle/{costcenter}', 'CostcenterController@toggleActive')->name('invoicerelease.costcenter.toggleActive');

        Route::resource('/invoicerelease/bills', 'BillController', ['as' => 'invoicerelease']);
        Route::resource('/invoicerelease/biller', 'BillerController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/ajax/', 'BillerController@showAjax')->name('invoicerelease.ajax');
        Route::get('/invoicerelease/ajax/{biller}', 'BillerController@showAjax')->name('invoicerelease.ajax.biller');

        Route::get('/invoicerelease/csv/bills', 'BillController@csv')->name('invoicerelease.bills.csv');
        Route::post('/invoicerelease/biller/csv', 'BillerController@csv')->name('invoicerelease.biller.csv');
        Route::get('/invoicerelease/bills/pdf/{filename}', 'BillItemController@loadFile')->name('invoicerelease.bills.pdf');

        Route::get('/invoicerelease/transactions/calendar', 'TransactionsController@calendar')->name('invoicerelease.transactions.calendar');
        Route::get('/invoicerelease/transactions/approval', 'TransactionsController@approval')->name('invoicerelease.transactions.approval');
        Route::get('/invoicerelease/transactions/unsettled', 'TransactionsController@unsettled')->name('invoicerelease.transactions.unsettled');
        Route::get('/invoicerelease/transactions/due_yesterday', 'TransactionsController@due_yesterday')->name('invoicerelease.transactions.due_yesterday');
        Route::post('/invoicerelease/transactions/status', 'TransactionsController@setStatus')->name('invoicerelease.transactions.status');
        Route::post('/invoicerelease/transactions/bills', 'TransactionsController@getBillsByDate')->name('invoicerelease.transactions.getBillsByDate');

resources/views/app/amazon.blade.php
@extends('app.layouts.app')


@section('content')

    <div class="container">

        <div class="card content-area">
            <div class="card-innr">
                <div class="card-head">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="card-title card-title-lg">Dashboard</h4>
                        </div>

                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-12">

                        <div class="card mt-2">
                            <div class="card-header">Amazom</div>


                        </div>

                    </div>
                </div>

            </div>
        </div>



    </div>

@endsection

resources/views/app/dashboard.blade.php
@extends('app.layouts.app')


@section('content')

    <div class="container">

        <div class="card content-area">
            <div class="card-innr">
                <div class="card-head">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="card-title card-title-lg">Dashboard</h4>
                        </div>

                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-12">

                        <div class="card mt-2">
                            <div class="card-header">Aufträge B2C</div>

                            <div class="card-body">

                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped mt-2 mb-3">
                                        <thead class="thead-dark">
                                        <tr>
                                            <th>Heute neu</th>
                                            <th>Letzten 7 Tage</th>
                                            <th>Nicht Übertragen</th>
                                            <th>Übertragungsfehler</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr id="">
                                            <?php
                                            $open = $settings['temp_orders'][0]->open ?? NULL;
                                            $error = $settings['temp_orders'][0]->error ?? NULL;
                                            ?>
                                            <td>{{ $settings['temp_orders'][0]->today ?? 'n.a' }}</td>
                                            <td>{{ $settings['temp_orders'][0]->week ?? 'n.a' }}</td>
                                            <td>{{ $open + $error }}</td>
                                            <td>{{ $error ?? 'n.a' }}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>

                                <form class="mb-0" id="submit-form" method="get" action="{{ route('app.temporder.dashboardSearch') }}">
                                    <input id="filter" name="filter" type="hidden" class="form-control" value="1" >
                                    @csrf
                                    <div class="input-group">
                                        <input id="quest" name="quest" type="text" class="form-control" placeholder="Suchbegriff" value="">
                                        <select  name="art" id="art" style="max-width: 170px;  cursor: pointer; color:#495057; border: 1px solid #ced4da; padding-top: 8px; border-radius: 0px; height: 37px !important;">
                                            @foreach (['number' => 'In Auftragsnummern', 'kunde' => 'In Kundendaten'] as $key=>$value)
                                                <option value="{{ $key }}">{{ $value }} </option>
                                            @endforeach
                                        </select>
                                        <button style="line-height: unset; padding: 0px; border-radius: 0px " type="submit" class="btn btn-secondary btn-search" >Suchen</button>
                                    </div>
                                </form>


                            </div>
                        </div>


                        @if(!empty($settings['bills']))
                        <div class="card mt-2">
                            <div class="card-header">Rechnungskontrolle</div>

                            <div class="card-body">

                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped mt-2 mb-3">
                                        <thead class="thead-dark">
                                        <tr>
                                            <th>Wartet auf Freigabe</th>
                                            <th>Zurückgestellt</th>
                                            <th>Mit Rückfragen</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr id="">
                                            <td><a style="color: black" href="{{ route('app.invoicerelease.bills.index') }}?filter=1&status=neu">{{ $settings['bills'][0]->neu ?? '' }} <i class="fas fa-link fa-sm "></i></a></td>
                                            <td><a style="color: black" href="{{ route('app.invoicerelease.bills.index') }}?filter=1&status=blocken">{{ $settings['bills'][0]->blocken ?? '' }} <i class="fas fa-link fa-sm "></i></a></td>
                                            <td><a style="color: black" href="{{ route('app.invoicerelease.bills.index') }}?filter=1&status=reklamieren">{{ $settings['bills'][0]->inquiry ?? '' }} <i class="fas fa-link fa-sm "></i></a></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                        @endif


                    </div>
                </div>

            </div>
        </div>



    </div>

@endsection