routes/web.php
    Route::get('/coupons/area/statistics/', 'CouponStatisticsController@index')->name('coupon.statistics');
    Route::get('/coupons/area/statistics/csv', 'CouponStatisticsController@exportCsv')->name('coupon.exportCsv');

    Route::get('/coupons/area/coupon/activetoggle/{coupon}', 'CouponController@toggleActive')->name('coupon.toggleActive');
    Route::get('/coupons/area/coupon/details/{coupon}', 'CouponController@details')->name('coupon.details');
    Route::get('/coupons/area/coupon/details/{coupon}/csv', 'CouponController@codesCsv')->name('coupon.codesCsv');

    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/show', 'ReviewsController@show')->name('reviews.show');
    Route::delete('/reviews/destroy', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::post('/reviews', 'ReviewsController@store')->name('reviews.store');

    Route::get('/topCategories', 'TopCategoriesController@index')->name('topCategories.index');
    Route::get('/topCategories/show/{topCategorie}', 'TopCategoriesController@show')->name('topCategories.show');
    Route::get('/topCategories/create', 'TopCategoriesController@create')->name('topCategories.create');
    Route::post('/topCategories', 'TopCategoriesController@store')->name('topCategories.store');
    Route::patch('/topCategories/{topCategorie}', 'TopCategoriesController@update')->name('topCategories.update');
    Route::delete('/topCategories/destroy/{topCategorie}', 'TopCategoriesController@destroy')->name('topCategories.destroy');
    Route::get('/topCategories/activetoggle/{topCategorie}', 'TopCategoriesController@toggleActive')->name('topCategories.toggleActive');


    Route::get('/topCategoriesEng', 'TopCategoriesEngController@index')->name('topCategoriesEng.index');
    Route::get('/topCategoriesEng/show/{topCategorie}', 'TopCategoriesEngController@show')->name('topCategoriesEng.show');
    Route::get('/topCategoriesEng/create', 'TopCategoriesEngController@create')->name('topCategoriesEng.create');
    Route::post('/topCategoriesEng', 'TopCategoriesEngController@store')->name('topCategoriesEng.store');
    Route::patch('/topCategoriesEng/{topCategorie}', 'TopCategoriesEngController@update')->name('topCategoriesEng.update');
    Route::delete('/topCategoriesEng/destroy/{topCategorie}', 'TopCategoriesEngController@destroy')->name('topCategoriesEng.destroy');
    Route::get('/topCategoriesEng/activetoggle/{topCategorie}', 'TopCategoriesEngController@toggleActive')->name('topCategoriesEng.toggleActive');

    Route::get('/gurado', 'GuradoController@index')->name('gurado.index');
    Route::get('/gurado/show', 'GuradoController@show')->name('gurado.show');
    Route::post('/gurado', 'GuradoController@store')->name('gurado.store');

    Route::get('/seal/activetoggle/{seal}', 'SealController@toggleActive')->name('seal.toggleActive');
    Route::get('/allergen/activetoggle/{allergen}', 'AllergenController@toggleActive')->name('allergen.toggleActive');
    Route::get('/productgroup/activetoggle/{productgroup}', 'ProductgroupController@toggleActive')->name('productgroup.toggleActive');
    Route::get('/manufacturer/activetoggle/{manufacturer}', 'ManufacturerController@toggleActive')->name('manufacturer.toggleActive');
    Route::post('/manufacturer/updateOrder', 'ManufacturerController@updateOrder')->name('manufacturer.updateOrder');

        // InvoiceRelease
    Route::namespace('InvoiceRelease')
        ->group(function () {

        Route::resource('/invoicerelease/costcenter', 'CostcenterController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/costcenter/activetoggle/{costcenter}', 'CostcenterController@toggleActive')->name('invoicerelease.costcenter.toggleActive');

        Route::resource('/invoicerelease/bills', 'BillController', ['as' => 'invoicerelease']);
        Route::resource('/invoicerelease/biller', 'BillerController', ['as' => 'invoicerelease']);
        Route::get('/invoicerelease/ajax/', 'BillerController@showAjax')->name('invoicerelease.ajax');
        Route::get('/invoicerelease/ajax/{biller}', 'BillerController@showAjax')->name('invoicerelease.ajax.biller');

        Route::get('/invoicerelease/csv/bills', 'BillController@csv')->name('invoicerelease.bills.csv');
        Route::post('/invoicerelease/biller/csv', 'BillerController@csv')->name('invoicerelease.biller.csv');
        Route::get('/invoicerelease/bills/pdf/{filename}', 'BillItemController@loadFile')->name('invoicerelease.bills.pdf');

        Route::get('/invoicerelease/transactions/calendar', 'TransactionsController@calendar')->name('invoicerelease.transactions.calendar');
        Route::get('/invoicerelease/transactions/approval', 'TransactionsController@approval')->name('invoicerelease.transactions.approval');
        Route::get('/invoicerelease/transactions/unsettled', 'TransactionsController@unsettled')->name('invoicerelease.transactions.unsettled');
        Route::get('/invoicerelease/transactions/due_yesterday', 'TransactionsController@due_yesterday')->name('invoicerelease.transactions.due_yesterday');
        Route::post('/invoicerelease/transactions/status', 'TransactionsController@setStatus')->name('invoicerelease.transactions.status');
        Route::post('/invoicerelease/transactions/bills', 'TransactionsController@getBillsByDate')->name('invoicerelease.transactions.getBillsByDate');

        Route::post('/invoicerelease/upload/bills/store', 'BillItemController@upload')->name('invoicerelease.bills.upload');
        Route::get('/invoicerelease/upload/bills/remove', 'BillItemController@removeFiles')->name('invoicerelease.bills.remove-files');

        Route::get('/info/biller/subjects', 'BillerController@match_subjects')->name('invoicerelease.biller.match_subjects');

        Route::get('/invoicerelease/payone/bills', 'PayonePaymentController@csv')->name('invoicerelease.payone.csv');
        Route::get('/invoicerelease/payone/bills_gurado', 'PayonePaymentController@csv_gurado')->name('invoicerelease.payone.csv_gurado');
        Route::get('/invoicerelease/payone', 'PayonePaymentController@index')->name('invoicerelease.payone');
        Route::get('/invoicerelease/payone/import', 'PayonePaymentController@importShow')->name('invoicerelease.payone.importShow');
        Route::post('/invoicerelease/payone/import', 'PayonePaymentController@import')->name('invoicerelease.payone.import');

 });

    // Customers
    Route::namespace('Customer')
        ->group(function () {
            Route::resource('/customer', 'CustomerController');
            Route::get('/customer/direct/{customer}', 'CustomerController@direct_edit')->name('customer.direct.edit');
            Route::get('/customer/direct/{customer}/address', 'CustomerController@direct_edit')->name('customer.direct.address');
            Route::get('/customer/activetoggle/{customer}', 'CustomerController@toggleActive')->name('customer.toggleActive');

            // address
            Route::get('/customer/{customer}/address', 'AddressController@index')->name('customer.address.index');
            Route::get('/customer/{customer}/address/create', 'AddressController@edit')->name('customer.address.create');
            Route::get('/customer/{customer}/address/{address}', 'AddressController@edit')->name('customer.address.edit');
            Route::patch('/customer/{customer}/address/{address}', 'AddressController@update')->name('customer.address.update');
            Route::post('/customer/{customer}/address', 'AddressController@store')->name('customer.address.store');
            Route::delete('/customer/{customer}/address/{address}', 'AddressController@destroy')->name('customer.address.destroy');
            Route::get('/customer/{customer}/address/{address}/togglePrimary', 'AddressController@togglePrimary')->name('customer.address.togglePrimary');

            // settings
            Route::get('/customer/{customer}/settings/create', 'SettingsController@create')->name('customer.settings.create');
            Route::post('/customer/{customer}/settings', 'SettingsController@store')->name('customer.settings.store');
            Route::get('/customer/{customer}/settings/edit', 'SettingsController@edit')->name('customer.settings.edit');
            Route::patch('/customer/{customer}/settings', 'SettingsController@update')->name('customer.settings.update');
            Route::delete('/customer/{customer}/settings', 'SettingsController@destroy')->name('customer.settings.destroy');

            // notes
            Route::get('/customer/{customer}/comment', 'CommentController@index')->name('customer.comment.index');
            Route::post('/customer/{customer}/comment', 'CommentController@store')->name('customer.comment.store');
            Route::delete('/customer/{customer}/comment/{comment}', 'CommentController@destroy')->name('customer.comment.destroy');

            // invoices
            #Route::get('/customer/{customer}/invoices', 'InvoiceController@index')->name('customer.invoices.index');

            // Orders
            #Route::get('/customer/{customer}/orders', 'OrderController@index')->name('customer.invoices.index');

        });


    // Customers
        /*
    Route::namespace('Product')
        ->group(function () {
            Route::resource('/product', 'ProductController');
            Route::get('/product/direct/{product}', 'ProductController@direct_edit')->name('product.direct.edit');
            Route::get('/product/activetoggle/{product}', 'ProductController@toggleActive')->name('product.toggleActive');

            // settings
            Route::get('/product/{product}/settings/create', 'SettingsController@create')->name('product.settings.create');
            Route::post('/product/{product}/settings', 'SettingsController@store')->name('product.settings.store');
            Route::get('/product/{product}/settings/edit', 'SettingsController@edit')->name('product.settings.edit');

app/Http/Controllers/App/InvoiceRelease/BillItemController.php
<?php

namespace App\Http\Controllers\App\InvoiceRelease;

use App\Actions\Files\Base64Decoder;
use App\Actions\Files\Pdf\CheckPdfFile;
use App\IrBillItem as BillItem;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;



class BillItemController extends Controller
{

    protected $filename = '';
    protected $path_absolut = '';

    private function createUniqueFileName() {
        return $this->filename = date("YmdHi").'-'.Str::uuid()->toString().'.pdf';
    }


    public function create($base64_file) {

        $this->path_absolut = $this->storeBase64File($base64_file);

        /*
        if (!(new CheckPdfFile())->handle($this->path_absolut)) {
            $this->deleteFile($this->path_absolut);
            return null;
        }
        */

        $bill_item = BillItem::create(['filename' => $this->filename, 'bill_id' => 0]);

        return $bill_item;

    }


    public function storeBase64File(string $base64_file)
    {
        $filename = $this->createUniqueFileName();

        // store original file
        if (!Storage::disk('invoicerelease')->put($filename, (new Base64Decoder())->handle($base64_file))) {
            abort(500, 'Error storing file');
        }

        return Storage::disk('invoicerelease')->path($filename);
    }


    public function loadFile(Request $request) {

        return response()->make(Storage::disk('invoicerelease')->get($request['filename']), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="Vorschau.pdf"'
        ]);

    }


    public function deleteFile(string $file_path_absolute)
    {
        return Storage::disk('invoicerelease')->delete(basename($file_path_absolute));
    }



    public function upload(Request $request)
    {
        $base64_file = base64_encode(file_get_contents($request->file->getRealPath()));

        $request->session()->push('upload.letter', $base64_file);
    }


    public function removeFiles(Request $request)
    {
        $request->session()->forget('upload.letter');
    }


}

app/Http/Controllers/App/InvoiceRelease/CostcenterController.php
<?php

namespace App\Http\Controllers\App\InvoiceRelease;

use App\Http\Controllers\Controller;
use App\IrCostcenter as Costcenter;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CostcenterController extends Controller
{


    public function _filterValidate()
    {
        $rules = [
            'filter' => 'sometimes|nullable|numeric',
            'filter_mandant' => 'sometimes|nullable|int',
            'filter_word' => 'sometimes|nullable|regex:/^[\w]+$/',
            'filter_row' => 'sometimes|nullable|required_with:filter_word,filter|string|regex:/^[\w]+$/',
            'filter_order' => 'sometimes|nullable|required_with:filter|string|in:desc,asc',
            'filter_active' => 'sometimes|nullable|numeric|in:1,0,-1',
        ];

        $attributes = [
            'filter' => 'Filter',
            'filter_mandant' => 'Mandant',
            'filter_word' => 'Suchbegriff',
            'filter_row' => 'Suchbereich',
            'filter_order' => 'Sortierung',
            'filter_active' => 'Aktive',
        ];

        $attributes = $this->validate(request(), $rules, array(), $attributes);

        return $attributes;
    }

    public function filterQuery($filter_attributes, $paginate=true)
    {
       $query = Costcenter::with(['mandant']);

        if (isset($filter_attributes['filter'])) {

            if (isset($filter_attributes['filter_word']) && $filter_attributes['filter_row'] != 1) {
                $query->where($filter_attributes['filter_row'], 'LIKE', '%' . $filter_attributes['filter_word'] . '%');
            }
            if (isset($filter_attributes['filter_mandant']) && $filter_attributes['filter_mandant'] != '') {
                $query->where('mandant_id', '=', $filter_attributes['filter_mandant']);
            }
            if (isset($filter_attributes['filter_active']) && $filter_attributes['filter_active'] != '') {
                if($filter_attributes['filter_active']!='-1') {
                    $query->where('active', '=', $filter_attributes['filter_active']);
                }
            }

            $query->orderBy($filter_attributes['filter_row'], $filter_attributes['filter_order']);
        }

        if(!$paginate) return $query->get();

        return $query->paginate($this->elements_per_page);
    }


    public function index()
    {
        $filter_attributes = $this->_filterValidate();

        $costcenters = $this->filterQuery($filter_attributes);

        return view('app.invoicerelease.costcenter.index')->with(['costcenter' => new Costcenter, 'costcenters' => $costcenters, 'filter_attributes' => $filter_attributes]);

    }

    public function show(Costcenter $costcenter)
    {
        return $this->edit($costcenter);
    }

    public function create(Costcenter $costcenter)
    {
        return $this->edit($costcenter);
    }


    public function edit(Costcenter $costcenter)
    {
        return view('app.invoicerelease.costcenter.edit')->with(['costcenter' => $costcenter]);
    }

    public function store()
    {
        $attributes = $this->_validate(new Costcenter());

        $costcenter = Costcenter::create([
            'name' => $attributes['name'],
            'value' => $attributes['value'],
            'mandant_id' => $attributes['mandant_id'],
        ]);

        return redirect(route('app.invoicerelease.costcenter.index'))->withSuccess($costcenter->presentation_short.' erfolgreich angelegt!');
    }


    public function update(Costcenter $costcenter)
    {
        $attributes = $this->_validate($costcenter);

        $costcenter->update([
            'name' => $attributes['name'],
            'value' => $attributes['value'],
            'mandant_id' => $attributes['mandant_id'],
        ]);


        return back()->withSuccess($costcenter->presentation_short.' bearbeitet!');
    }


    public function destroy(Costcenter $costcenter)
    {
        $costcenter->delete();
        return back()->withDanger($costcenter->presentation_short.' gelöscht!');
    }


    public function _validate()
    {
        $attributes = request()->validate([
            'mandant_id' => 'required|not_in:0',
            'name' => 'required|string|min:2|max:50',
            'value' => 'string|min:2|max:15',
        ]);

        return $attributes;
    }

    public function toggleActive(Costcenter $costcenter) {
        $costcenter->update(['active' => !$costcenter->active]);
        return back()->withSuccess($costcenter->presentation_short.' wurde '.(!$costcenter->active?'deaktiviert':'aktiviert'));
    }


}

resources/views/app/invoicerelease/transactions/_billsTableWithOptions.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-striped mt-2 mb-3">
        <thead class="thead-dark">
        <tr>
            <th>Fällig am</th>
            <th>Empfangen am</th>
            <th>Mandant</th>
            <th>Rechnungssteller</th>
            <th>Rechnungsnummer</th>
            <th>Freigabeabteilung</th>
            <th>Zahlart</th>
            <th class="text-right" style="min-width: 115px;">Betrag</th>
            <th>Status</th>
            <th>Aktionen
                <i style="font-size: 18px; float: right; margin-right: 5px; margin-top:3px" data-toggle="tooltip" data-html="true" title="Beim ändern einer Aktion wird dies unmittelbar als neuer Status gespeichert!" data-original-title="Hinweis: Durch verändern einer Aktion wird diese unmittelbar als neuer Status gespeichert!" class="fas fa-info-circle"></i>
            </th>
            @headicons('1', 'fa-eye')
        </tr>
        </thead>
        <tbody>
        @forelse ( $bills AS $bill )
            <?php
            switch ($bill->status) {

                case 'not_assigned' :  $status_text='Nicht zugeordnet'; $status_color='#000'; break;
                case 'neu' :  $status_text='Wartet auf Freigabe'; $status_color='#000'; break;
                case 'vorab_freigabe' :  $status_text='Vorab-Freigegeben'; $status_color='#000'; break;
                case 'freigabe' :  $status_text='Freigegeben'; $status_color='#000'; break;
                case 'bezahlt' :  $status_text='Bezahlt'; $status_color='#2fb986 ; font-weight: bolder;'; break;
                case 'bezahlen' :  $status_text='Kann bezahlt werden'; $status_color='#000'; break;
                case 'blocken' :  $status_text='Bezahlung zurückhalten'; $status_color='#000'; break;
                case 'reklamieren' :  $status_text='Reklamiert'; $status_color='#000'; break;
                default : $status_text='Fehler'; $status_color='#000'; break;
            }
            ?>
            <tr id="">
                <td>{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $bill->due_date)->format('d.m.Y') }}</td>
                <td class="text-right">@date($bill->created_at)</td>
                <td>{{ $bill->mandant }}</td>
                <td>{{ $bill->biller }}</td>
                <td>{{ $bill->bill_number }}</td>
                <td>{{ $bill->department }}</td>
                <td>{{ $bill->payment_method }} </td>
                <td class="text-right">@money($bill->amount)</td>
                <td  id="status_{{$bill->id}}" style="color: {{ $status_color }};">{{ $status_text }}</td>
                <td>
                    <select class="input-bordered aktion" name="aktion" data-id="{{$bill->id}}">
                        <option value="0">Bitte wählen</option>
                        <option value="blocken">Zahlung zurückstellen</option>
                        <option value="reklamieren" >Rechnung reklamieren</option>
                        <option value="bezahlt" >Als bezahlt markieren</option>
                        <!-- <option value="bezahlen" {{ $bill->status== 'bezahlen' ? 'selected="selected"' : '' }}>Zahlung einleiten</option> -->
                        <!-- <option value="blocken" {{ $bill->status== 'blocken' ? 'selected="selected"' : '' }}>Zahlung zurückstellen</option> -->
                        <!-- <option value="reklamieren" {{ $bill->status== 'reklamieren' ? 'selected="selected"' : '' }}>Rechnung reklamieren</option> -->
                        <!-- <option value="bezahlt" {{ $bill->status== 'bezahlt' ? 'selected="selected"' : '' }}>Als bezahlt markieren</option> -->
                    </select>
                </td>
                <td><a target="_blank" title="Rechnung einsehen" href="{{ route('app.invoicerelease.bills.edit', ['bill'=>$bill->id] ) }}"><i class="far fa-eye"></i></a>  </td>
            </tr>
        @empty
            <tr id=""><td colspan="100%">Keine {{ $bill->presentation_long }} vorhanden</td></tr>
        @endforelse
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $('.aktion').on('change', function () {

        var status = $(this).val();
        var bill_id = $(this).attr('data-id');
        var element = $(this);
        var element_status = $('#status_'+bill_id);

        var status_text = '';
        switch (status) {
            case 'not_assigned' :  status_text='Nicht zugeordnet';  break;
            case 'neu' :  status_text='Wartet auf Freigabe';  break;
            case 'vorab_freigabe' :  status_text='Vorab-Freigegeben'; break;
            case 'freigabe' :  status_text='Freigegeben';  break;
            case 'bezahlt' :  status_text='Bezahlt';  break;
            case 'bezahlen' :  status_text='Kann bezahlt werden';  break;
            case 'blocken' :  status_text='Bezahlung zurückhalten';  break;
            case 'reklamieren' :  status_text='Reklamiert'; break;
            default : status_text='Fehler';  break;
        }

        $.ajax({
            url: '{{ route('app.invoicerelease.transactions.status') }}',
            type: 'POST',
            data: {
                "_token": "{{ csrf_token() }}",
                "status" : status,
                "id" : bill_id,
            },
            success: function(data) {
                var color_first = 'initial';
                var color_last = '#e81515';
                if(data) {
                    color_first = '#54ff5e';
                    color_last = 'initial';
                }
                else {
                    element.css('color', '#fff');
                }
                element.css('background', color_first);
                element_status.html(status_text);
                setTimeout(function(){
                    element.css('background', color_last);
                }, 750);
            }
        });

    })

</script>

resources/views/app/invoicerelease/transactions/_billsTableWithOptionsSortable.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-striped mt-2 mb-3">
        <thead class="thead-dark">
        <tr>
            <th>@sortablelink('due_date', 'Fällig am')</th>
            <th>@sortablelink('created_at', 'Empfangen am')</th>
            <th>@sortablelink('mandant.name', 'Mandant')</th>
            <th>@sortablelink('biller.name', 'Rechnungssteller')</th>
            <th>@sortablelink('bill_number', 'Rechnungsnummer')</th>
            <th>@sortablelink('department.name', 'Freigabeabteilung')</th>
            <th>@sortablelink('costcenter.value', 'Kostenstelle')</th>
            <th>@sortablelink('payment_method', 'Zahlart')</th>
            <th class="text-right">@sortablelink('amount', 'Betrag')</th>
            <th>@sortablelink('status', 'Status')</th>
            <th>Aktionen
                <i style="font-size: 18px; float: right; margin-right: 5px; margin-top:3px" data-toggle="tooltip" data-html="true" title="Beim ändern einer Aktion wird dies unmittelbar als neuer Status gespeichert!" data-original-title="Hinweis: Durch verändern einer Aktion wird diese unmittelbar als neuer Status gespeichert!" class="fas fa-info-circle"></i>
            </th>
            @headicons('1', 'fa-eye')
        </tr>
        </thead>
        <tbody>
        @forelse ( $bills AS $bill )
            <?php
            switch ($bill->status) {

                case 'not_assigned' :  $status_text='Nicht zugeordnet'; $status_color='#000'; break;
                case 'neu' :  $status_text='Wartet auf Freigabe'; $status_color='#000'; break;
                case 'vorab_freigabe' :  $status_text='Vorab-Freigegeben'; $status_color='#000'; break;
                case 'freigabe' :  $status_text='Freigegeben'; $status_color='#000'; break;
                case 'bezahlt' :  $status_text='Bezahlt'; $status_color='#2fb986 ; font-weight: bolder;'; break;
                case 'bezahlen' :  $status_text='Kann bezahlt werden'; $status_color='#000'; break;
                case 'blocken' :  $status_text='Bezahlung zurückhalten'; $status_color='#000'; break;
                case 'reklamieren' :  $status_text='Reklamiert'; $status_color='#000'; break;
                default : $status_text='Fehler'; $status_color='#000'; break;
            }
            ?>
            <tr id="">
                <td>{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $bill->due_date)->format('d.m.Y') }}</td>
                <td class="text-right">@date($bill->created_at)</td>
                <td>{{ ( empty($bill->mandant) ? '' : $bill->mandant->short_name) }}</td>
                <td>{{ ( empty($bill->biller) ? '' : $bill->biller->name) }}</td>
                <td>{{ $bill->bill_number }}</td>
                <td>{{ ( empty($bill->department) ? '' :  $bill->department->name ) }}
                <td>{{ ( empty($bill->costcenter) ? '' :  $bill->costcenter->value )  }}
                <td>{{ $bill->payment_method }} </td>
                <td class="text-right">@money($bill->amount)</td>
                <td id="status_{{$bill->id}}" style="color: {{ $status_color }};">{{ $status_text }}</td>
                <td>
                    <select class="input-bordered aktion" name="aktion" data-id="{{$bill->id}}">
                        <option value="0">Bitte wählen</option>
                        <option value="blocken">Zahlung zurückstellen</option>
                        <option value="reklamieren" >Rechnung reklamieren</option>
                        <option value="bezahlt" >Als bezahlt markieren</option>
                        <!-- <option value="bezahlen" {{ $bill->status== 'bezahlen' ? 'selected="selected"' : '' }}>Zahlung einleiten</option> -->
                        <!-- <option value="blocken" {{ $bill->status== 'blocken' ? 'selected="selected"' : '' }}>Zahlung zurückstellen</option> -->
                        <!-- <option value="reklamieren" {{ $bill->status== 'reklamieren' ? 'selected="selected"' : '' }}>Rechnung reklamieren</option> -->
                        <!-- <option value="bezahlt" {{ $bill->status== 'bezahlt' ? 'selected="selected"' : '' }}>Als bezahlt markieren</option> -->
                    </select>
                </td>
                <td><a target="_blank" title="Rechnung einsehen" href="{{ route('app.invoicerelease.bills.edit', ['bill'=>$bill->id] ) }}"><i class="far fa-eye"></i></a>  </td>
            </tr>
        @empty
            <tr id=""><td colspan="100%">Keine {{ $bill->presentation_long }} vorhanden</td></tr>
        @endforelse
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $('.aktion').on('change', function () {

        var status = $(this).val();
        var bill_id = $(this).attr('data-id');
        var element = $(this);
        var element_status = $('#status_'+bill_id);

        var status_text = '';
        switch (status) {
            case 'not_assigned' :  status_text='Nicht zugeordnet';  break;
            case 'neu' :  status_text='Wartet auf Freigabe';  break;
            case 'vorab_freigabe' :  status_text='Vorab-Freigegeben'; break;
            case 'freigabe' :  status_text='Freigegeben';  break;
            case 'bezahlt' :  status_text='Bezahlt';  break;
            case 'bezahlen' :  status_text='Kann bezahlt werden';  break;
            case 'blocken' :  status_text='Bezahlung zurückhalten';  break;
            case 'reklamieren' :  status_text='Reklamiert'; break;
            default : status_text='Fehler';  break;
        }

        $.ajax({
            url: '{{ route('app.invoicerelease.transactions.status') }}',
            type: 'POST',
            data: {
                "_token": "{{ csrf_token() }}",
                "status" : status,
                "id" : bill_id,
            },
            success: function(data) {
                var color_first = 'initial';
                var color_last = '#e81515';
                if(data) {
                    color_first = '#54ff5e';
                    color_last = 'initial';
                }
                else {
                    element.css('color', '#fff');
                }
                element.css('background', color_first);
                element_status.html(status_text);
                setTimeout(function(){
                    element.css('background', color_last);
                }, 750);
            }
        });

    })

</script>

resources/views/app/invoicerelease/transactions/_due_yesterday.blade.php
@section('container-class') container-fluid @endsection
@extends('app.invoicerelease.transactions.index')
@section('transactions')
    <div id="calendar" class="tab-pane mt-3 active">
        <div class="row">

            <div class="col-md-12">
                @include('app.invoicerelease.transactions._billsTableWithOptions')
            </div>
        </div>

        <div class="row justify-content-md-center">
            {{ $bills->withQueryString()->links() }}
        </div>

    </div>
    </div>

@endsection